# Generated by Django 3.2.9 on 2021-11-21 18:43

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_info',
            field=models.TextField(null=True, verbose_name='User info'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits, dots and underlines only.', max_length=30, unique=True, validators=[users.models.CustomUnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
