# Generated by Django 3.2.9 on 2021-11-21 18:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Pool users'),
        ),
    ]
