# Generated by Django 3.2.9 on 2021-11-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0002_pool_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='description',
            field=models.TextField(null=True, verbose_name='Pool description'),
        ),
    ]
